dark_mode:
    enable: true
    default: auto

navbar:
    blog_title: "Flysoft 的小站"

static_prefix:
    jquery: https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/
    nprogress: https://cdn.jsdelivr.net/npm/nprogress@0.2.0/
    bootstrap: https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/

index:
    slogan:
        text: "代码改变世界！"

fun_features:
    typing:
        enable: false

post:
    math:
        enable: true
        specific: true
        engine: mathjax

custom_css: /css/custom.css

favicon: /img/favicon.png

apple_touch_icon: /img/favicon.png
