dark_mode:
    enable: true
    default: auto

navbar:
    blog_title: "Flysoft 的小站"

static_prefix:
    jquery: https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/
    nprogress: https://cdn.jsdelivr.net/npm/nprogress@0.2.0/
    bootstrap: https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/

index:
    slogan:
        text: "代码改变世界！"

fun_features:
    typing:
        enable: false

post:
    math:
        enable: true
        specific: true
        engine: mathjax

footer:
    content: '<a href="/privacy-policy" target="_blank" rel="nofollow noopener"><span>隐私政策</span></a><span> | © Flysoft</span><br><a href="https://hexo.io" target="_blank" rel="nofollow noopener"><span>Hexo</span></a> <i class="iconfont icon-love"></i> <a href="https://github.com/fluid-dev/hexo-theme-fluid" target="_blank" rel="nofollow noopener"><span>Fluid</span></a>'

custom_css: /css/custom.css

favicon: /img/favicon.png

apple_touch_icon: /img/favicon.png
