name: Pages

on:
    push:
        branches:
            - main

jobs:
    pages:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pages: write
            id-token: write
        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  submodules: recursive
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Cache NPM dependencies
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: ${{ runner.os }}-npm-cache
                  restore-keys: |
                      ${{ runner.os }}-npm-cache
            - name: Install Dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v1
              with:
                  path: ./public
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
